export const db = {
  candidats: [
    {
      id: 1,
      nom: 'Benali',
      prenom: 'Sara',
      email: 'sara.benali@example.com',
      telephone: '06 11 22 33 44',
      categorie: 'B',
      statut: 'EN_COURS',
      montantTotal: 1400,
      dateInscription: '2026-01-15T09:00:00.000Z',
    },
    {
      id: 2,
      nom: 'Martin',
      prenom: 'Leo',
      email: 'leo.martin@example.com',
      telephone: '06 55 44 33 22',
      categorie: 'B',
      statut: 'EN_ATTENTE',
      montantTotal: 1200,
      dateInscription: '2026-02-04T10:30:00.000Z',
    },
    {
      id: 3,
      nom: 'Dupont',
      prenom: 'Nina',
      email: 'nina.dupont@example.com',
      telephone: '07 11 99 88 77',
      categorie: 'B',
      statut: 'RECU',
      montantTotal: 980,
      dateInscription: '2025-11-20T14:15:00.000Z',
    },
  ],
  paiements: [
    {
      id: 1,
      candidatId: 1,
      montant: 350,
      date: '2026-05-01T09:30:00.000Z',
      mode: 'CARTE',
      reference: 'CB-4421',
      note: 'Acompte inscription',
      factureId: 1,
    },
    {
      id: 2,
      candidatId: 1,
      montant: 280,
      date: '2026-05-03T11:00:00.000Z',
      mode: 'VIREMENT',
      reference: 'VIR-7751',
      note: '',
      factureId: 1,
    },
    {
      id: 3,
      candidatId: 2,
      montant: 120,
      date: '2026-05-04T16:40:00.000Z',
      mode: 'ESPECES',
      reference: '',
      note: 'Reglement partiel',
      factureId: 2,
    },
  ],
  factures: [
    {
      id: 1,
      numero: 'FAC-2026-001',
      candidatId: 1,
      montantTotal: 1400,
      statut: 'PARTIELLEMENT_PAYEE',
    },
    {
      id: 2,
      numero: 'FAC-2026-002',
      candidatId: 2,
      montantTotal: 1200,
      statut: 'EN_ATTENTE',
    },
  ],
  caisse: [
    {
      id: 1,
      type: 'ENTREE',
      montant: 350,
      solde: 350,
      description: 'Paiement - Sara Benali',
      reference: 'PAI-1',
      date: '2026-05-01T09:30:00.000Z',
    },
    {
      id: 2,
      type: 'ENTREE',
      montant: 280,
      solde: 630,
      description: 'Paiement - Sara Benali',
      reference: 'PAI-2',
      date: '2026-05-03T11:00:00.000Z',
    },
    {
      id: 3,
      type: 'ENTREE',
      montant: 120,
      solde: 750,
      description: 'Paiement - Leo Martin',
      reference: 'PAI-3',
      date: '2026-05-04T16:40:00.000Z',
    },
  ],
  depenses: [
    {
      id: 1,
      categorie: 'CARBURANT',
      montant: 95,
      description: 'Plein Peugeot 208',
      date: '2026-05-02T08:00:00.000Z',
    },
  ],
  vehicules: [
    {
      id: 1,
      immatriculation: 'AB-123-CD',
      marque: 'Peugeot',
      modele: '208',
      annee: 2023,
      categorie: 'B',
      kilometrage: 24250,
      statut: 'DISPONIBLE',
    },
    {
      id: 2,
      immatriculation: 'EF-456-GH',
      marque: 'Renault',
      modele: 'Clio V',
      annee: 2022,
      categorie: 'B',
      kilometrage: 31700,
      statut: 'EN_ENTRETIEN',
    },
  ],
  moniteurs: [
    {
      id: 1,
      nom: 'Henry',
      prenom: 'Marc',
      email: 'marc.henry@example.com',
      telephone: '06 10 10 10 10',
      specialite: 'Conduite',
      actif: true,
    },
    {
      id: 2,
      nom: 'Da Silva',
      prenom: 'Paula',
      email: 'paula.silva@example.com',
      telephone: '06 20 20 20 20',
      specialite: 'Conduite accompagnee',
      actif: true,
    },
  ],
  lecons: [
    {
      id: 1,
      date: '2026-05-08T14:00:00.000Z',
      duree: 90,
      type: 'CONDUITE',
      statut: 'PLANIFIEE',
      candidatId: 1,
      moniteurId: 1,
      vehiculeId: 1,
    },
  ],
}

export function nextId(collection) {
  return collection.length ? Math.max(...collection.map((item) => item.id)) + 1 : 1
}
